# Name for the experiment
project_name: ""

samples: config/samplesheet.tsv
##### REFERENCE FILES #####
# Name of the genome or transcriptome fasta file to align on
fasta: ""

# Name of the gff file with genome or transcriptome annotations
gff: ""

# Fasta file with unwanted ribosomal RNA sequences (can be left empty)
rRNA: ""

# Fasta file with unwanted tRNA sequences (can be left empty)
tRNA: ""

##### TRIMMING #####
# Are the sequencing adapters already removed in fastq files ? 'yes' or 'no'
already_trimmed: ""

# Adapter sequence (Example sequence for Illumina TruSeq™ single or CD index : "AGATCGGAAGAGCACACGTCTGAACTCCAGTCA")
# Put "" if unknown, RiboDoc_BAM2Reads will try to find it for you
adapt_sequence: ""


##### LENGTHS SELECTION #####
# Minimum read length kept for ribosome profiling
readsLength_min: "25"

# Maximum read length kept for ribosome profiling
readsLength_max: "35"


##### GFF #####
# Feature of the annotation file to select during counting (usually "CDS")
gff_cds_feature: "CDS"

# Feature defining a transcript (usually "mRNA" or "transcript")
gff_mRNA_feature: "mRNA"

# Feature defining a 5-prime_UTR (usually "five_prime_UTR" or "5UTR")
gff_5UTR_feature: "five_prime_UTR"

# Attribut linking CDS to its related transcript feature in the annotation file (usually "Parent")
gff_parent_attribut: "Parent"

# Attribut containing the name of the feature in the annotation file (usually 'Name')
gff_name_attribut: "Name"


##### DIFFERENTIAL ANALYSIS #####
# Name of the reference condition (same as file name) for DESeq2
reference_condition: ""

# Other conditions to compare to the reference condition above for DESeq2
conditions: ""

# Thresholds to adjust for differential expression analysis
p-val: "0.01"
logFC: "0"


##### QUALITATIVE ANALYSIS #####
# Choose between "ribowaltz" or "trip"
# riboWaltz may require a lot of ressources but is more accurate and find Psite offsets
qualitative_analysis: "ribowaltz"

# Number of bases to look before the start and after the stop for periodicity (relative positions)
window_utr: "30"

# Number of bases to look after the start and before the stop for periodicity (relative positions)
window_cds: "90"


# Codon Occupancy
# Do you want to perform codon occupancy analysis ? 'yes' or 'no'
codon_occupancy: ""

# Ribosomal decoding site to analyze ('A' or 'P')
site: ""

########## OPTIONAL ##########
# Does UTR covering has to be calculated ("yes" or "no")
UTR: "no"

# Feature defining a 3-prime_UTR in GFF file (usually "three_prime_UTR" or "3UTR")
gff_3UTR_feature: "three_prime_UTR"

# Number of nucleotides before the start and after the stop codon to keep for transcript elongation
elongation: "50"
##############################
